import type { DemoCategory, DemoProduct, DemoSeller, DemoUser } from "@/lib/types";

export const demoUsers: DemoUser[] = [
  {
    id: "buyer-1",
    name: "Ariana Cole",
    email: "buyer1@neuromarket.dev",
    password: "password123",
    role: "BUYER",
    isEmailVerified: true,
  },
  {
    id: "seller-1-user",
    name: "Miles Kent",
    email: "seller1@neuromarket.dev",
    password: "password123",
    role: "SELLER",
    sellerId: "seller-1",
    isEmailVerified: true,
  },
  {
    id: "seller-2-user",
    name: "Nora Vale",
    email: "seller2@neuromarket.dev",
    password: "password123",
    role: "SELLER",
    sellerId: "seller-2",
    isEmailVerified: true,
  },
  {
    id: "admin-1",
    name: "Admin NeuroMarket",
    email: "admin@neuromarket.dev",
    password: "password123",
    role: "ADMIN",
    isEmailVerified: true,
  },
];

export const demoSellers: DemoSeller[] = [
  {
    id: "seller-1",
    displayName: "SignalForge",
    country: "Poland",
    rating: 4.9,
    bio: "Official partner bundles for AI subscriptions, coding assistants, and agency seats.",
    verified: true,
    pendingBalance: 980,
    availableBalance: 3260,
    withdrawnBalance: 14500,
    responseTime: "within 12 min",
  },
  {
    id: "seller-2",
    displayName: "PromptHarbor",
    country: "Estonia",
    rating: 4.8,
    bio: "Digital kits, onboarding files, and premium productivity access packs for creators.",
    verified: true,
    pendingBalance: 610,
    availableBalance: 1820,
    withdrawnBalance: 9300,
    responseTime: "within 18 min",
  },
  {
    id: "seller-3",
    displayName: "AIAcademy Labs",
    country: "Serbia",
    rating: 4.7,
    bio: "Course drops, voucher campaigns, and launch bundles for teams scaling AI adoption.",
    verified: false,
    pendingBalance: 220,
    availableBalance: 540,
    withdrawnBalance: 4100,
    responseTime: "within 30 min",
  },
];

export const demoCategories: DemoCategory[] = [
  {
    id: "chatgpt",
    slug: "chatgpt",
    label: "ChatGPT",
    teaser: "GPT seats & pro access",
    accent: "#f97316",
  },
  {
    id: "claude",
    slug: "claude",
    label: "Claude",
    teaser: "Reasoning workflows",
    accent: "#8b5cf6",
  },
  {
    id: "midjourney",
    slug: "midjourney",
    label: "Midjourney",
    teaser: "Image generation",
    accent: "#ec4899",
  },
  { id: "cursor", slug: "cursor", label: "Cursor", teaser: "Coding copilots", accent: "#38bdf8" },
  { id: "gemini", slug: "gemini", label: "Gemini", teaser: "Workspace AI", accent: "#22c55e" },
  {
    id: "perplexity",
    slug: "perplexity",
    label: "Perplexity",
    teaser: "Research agents",
    accent: "#06b6d4",
  },
  {
    id: "copilot",
    slug: "copilot",
    label: "Copilot Pro",
    teaser: "Microsoft stack",
    accent: "#3b82f6",
  },
  { id: "canva", slug: "canva", label: "Canva", teaser: "Design subscriptions", accent: "#14b8a6" },
  { id: "capcut", slug: "capcut", label: "CapCut", teaser: "Creator editing", accent: "#ef4444" },
  {
    id: "services",
    slug: "services",
    label: "Services",
    teaser: "Setup & consulting",
    accent: "#f59e0b",
  },
];

const faq = [
  {
    question: "Как быстро приходит доступ?",
    answer:
      "Моментальные позиции выдаются сразу после оплаты. Для ручной доставки указывается точное SLA продавца.",
  },
  {
    question: "Что делать, если нужен refund?",
    answer:
      "До активации можно открыть dispute. Для цифровых файлов действует политика, указанная в карточке.",
  },
];

export const demoProducts: DemoProduct[] = [
  {
    id: "p-chatgpt-team",
    slug: "chatgpt-team-workspace-bundle",
    title: "ChatGPT Team Workspace Bundle",
    shortDescription:
      "Shared AI workspace for content, ops, and support teams with instant access.",
    description:
      "A ready-to-activate seat bundle tailored for agencies and growth teams that need fast GPT workflows, shared prompt playbooks, and managed renewal support.",
    price: 29.99,
    originalPrice: 44.99,
    rating: 4.9,
    ratingCount: 128,
    salesCount: 930,
    sellerId: "seller-1",
    categoryId: "chatgpt",
    productType: "LICENSE_KEY",
    deliveryType: "INSTANT",
    status: "PUBLISHED",
    verified: true,
    smart: true,
    coverage: "Global",
    validity: "30 days",
    refundPolicy: "Refund before activation or within buyer protection review.",
    termsOfUse: "One active workspace transfer, resale prohibited, legal business usage only.",
    whatYouReceive: ["Activation key", "Onboarding checklist", "Usage notes"],
    faq,
    cover: { from: "#f97316", via: "#fb923c", to: "#facc15", glyph: "GPT", eyebrow: "SMART DEAL" },
  },
  {
    id: "p-claude-pro",
    slug: "claude-pro-research-pass",
    title: "Claude Pro Research Pass",
    shortDescription:
      "Reasoning-heavy subscription for analysts, founders, and deep work sessions.",
    description:
      "A premium Claude pass configured for long-form synthesis, policy drafting, and fast delivery with verified seller handling.",
    price: 24.99,
    originalPrice: 34.99,
    rating: 4.8,
    ratingCount: 84,
    salesCount: 602,
    sellerId: "seller-1",
    categoryId: "claude",
    productType: "VOUCHER_CODE",
    deliveryType: "INSTANT",
    status: "PUBLISHED",
    verified: true,
    smart: true,
    coverage: "EU / US",
    validity: "30 days",
    refundPolicy: "Refund if code is invalid or duplicate.",
    termsOfUse: "Single-user use, commercial writing allowed, no shared credentials.",
    whatYouReceive: ["Voucher code", "Redeem guide", "Priority support"],
    faq,
    cover: { from: "#7c3aed", via: "#a855f7", to: "#f97316", glyph: "CL", eyebrow: "VERIFIED" },
  },
  {
    id: "p-midjourney-studio",
    slug: "midjourney-studio-monthly-pass",
    title: "Midjourney Studio Monthly Pass",
    shortDescription:
      "Commercial image subscription pack for fast concept art and campaign mockups.",
    description:
      "Designed for design teams that need a predictable Midjourney workflow, support on activation, and a marketplace-backed purchase trail.",
    price: 22.99,
    originalPrice: 31.99,
    rating: 4.8,
    ratingCount: 96,
    salesCount: 511,
    sellerId: "seller-2",
    categoryId: "midjourney",
    productType: "LICENSE_KEY",
    deliveryType: "INSTANT",
    status: "PUBLISHED",
    verified: true,
    smart: false,
    coverage: "Global",
    validity: "30 days",
    refundPolicy: "Refund before redemption only.",
    termsOfUse: "Personal or commercial creation allowed under platform terms.",
    whatYouReceive: ["Account upgrade token", "Prompt starter pack", "Commercial use notes"],
    faq,
    cover: { from: "#111827", via: "#ec4899", to: "#fb923c", glyph: "MJ", eyebrow: "HOT" },
  },
  {
    id: "p-cursor-max",
    slug: "cursor-max-dev-seat",
    title: "Cursor Max Dev Seat",
    shortDescription: "AI coding seat with repo-aware setup notes for engineering teams.",
    description:
      "A developer-focused access package for teams standardizing on code generation, refactors, and pair-programming workflows.",
    price: 31.99,
    originalPrice: 47.99,
    rating: 4.9,
    ratingCount: 73,
    salesCount: 444,
    sellerId: "seller-1",
    categoryId: "cursor",
    productType: "LICENSE_KEY",
    deliveryType: "INSTANT",
    status: "PUBLISHED",
    verified: true,
    smart: true,
    coverage: "Global",
    validity: "30 days",
    refundPolicy: "Refund before activation.",
    termsOfUse: "Single seat, business use allowed, no credential resale.",
    whatYouReceive: ["Activation key", "IDE setup guide", "Priority support"],
    faq,
    cover: { from: "#0f172a", via: "#38bdf8", to: "#f97316", glyph: "</>", eyebrow: "DEV TOOLS" },
  },
  {
    id: "p-gemini-workspace",
    slug: "gemini-workspace-pro-credit-pack",
    title: "Gemini Workspace Pro Credit Pack",
    shortDescription: "Flexible Google AI credits for docs, slides, and internal research.",
    description:
      "Built for operators who need reusable AI capacity across Google workflows with fast activation and buyer protection.",
    price: 27.49,
    originalPrice: 39.99,
    rating: 4.7,
    ratingCount: 61,
    salesCount: 298,
    sellerId: "seller-2",
    categoryId: "gemini",
    productType: "VOUCHER_CODE",
    deliveryType: "INSTANT",
    status: "PUBLISHED",
    verified: true,
    smart: false,
    coverage: "Global",
    validity: "90 days",
    refundPolicy: "Refund on failed redemption only.",
    termsOfUse: "Managed through official workspace billing rules.",
    whatYouReceive: ["Credit voucher", "Redeem notes", "Scope matrix"],
    faq,
    cover: { from: "#22c55e", via: "#14b8a6", to: "#3b82f6", glyph: "G", eyebrow: "TOP SELLER" },
  },
  {
    id: "p-perplexity-research",
    slug: "perplexity-research-team-license",
    title: "Perplexity Research Team License",
    shortDescription: "Source-backed search subscription for strategy, media, and market teams.",
    description:
      "A polished team-ready access pack for fast research, citation workflows, and analyst-grade competitive monitoring.",
    price: 19.99,
    originalPrice: 28.99,
    rating: 4.7,
    ratingCount: 44,
    salesCount: 241,
    sellerId: "seller-1",
    categoryId: "perplexity",
    productType: "LICENSE_KEY",
    deliveryType: "INSTANT",
    status: "PUBLISHED",
    verified: true,
    smart: true,
    coverage: "Global",
    validity: "30 days",
    refundPolicy: "Refund before first use.",
    termsOfUse: "Per-seat licensing only.",
    whatYouReceive: ["Activation key", "Research templates", "Usage guide"],
    faq,
    cover: { from: "#164e63", via: "#06b6d4", to: "#eab308", glyph: "PX", eyebrow: "DAILY DEAL" },
  },
  {
    id: "p-copilot-pro",
    slug: "copilot-pro-focus-license",
    title: "Copilot Pro Focus License",
    shortDescription:
      "Microsoft ecosystem AI for docs, mail, and productivity-heavy knowledge work.",
    description:
      "A streamlined license offer for professionals who live in the Microsoft stack and need fast, low-friction delivery.",
    price: 23.49,
    originalPrice: 33.49,
    rating: 4.6,
    ratingCount: 35,
    salesCount: 187,
    sellerId: "seller-2",
    categoryId: "copilot",
    productType: "LICENSE_KEY",
    deliveryType: "INSTANT",
    status: "PUBLISHED",
    verified: true,
    smart: false,
    coverage: "Global",
    validity: "30 days",
    refundPolicy: "Refund before redemption.",
    termsOfUse: "Single-user access only.",
    whatYouReceive: ["License token", "Setup notes", "Buyer protection"],
    faq,
    cover: {
      from: "#1d4ed8",
      via: "#3b82f6",
      to: "#22c55e",
      glyph: "CP",
      eyebrow: "FAST DELIVERY",
    },
  },
  {
    id: "p-canva-suite",
    slug: "canva-brand-suite-subscription",
    title: "Canva Brand Suite Subscription",
    shortDescription: "Brand kit oriented design access for marketers and social teams.",
    description:
      "A quick-start digital product for teams who need templates, brand consistency, and managed subscription sourcing.",
    price: 16.99,
    originalPrice: 25.99,
    rating: 4.8,
    ratingCount: 52,
    salesCount: 323,
    sellerId: "seller-2",
    categoryId: "canva",
    productType: "LICENSE_KEY",
    deliveryType: "INSTANT",
    status: "PUBLISHED",
    verified: true,
    smart: true,
    coverage: "Global",
    validity: "30 days",
    refundPolicy: "Refund before activation.",
    termsOfUse: "Single brand workspace. No account resale.",
    whatYouReceive: ["Activation code", "Brand template bundle", "Usage notes"],
    faq,
    cover: { from: "#0f766e", via: "#14b8a6", to: "#38bdf8", glyph: "CA", eyebrow: "CREATOR PICK" },
  },
  {
    id: "p-capcut-pro",
    slug: "capcut-pro-editor-pack",
    title: "CapCut Pro Editor Pack",
    shortDescription: "Creator editing subscription with instant delivery and support notes.",
    description:
      "A compact offer for solo creators and agencies producing vertical content with predictable turnaround and buyer coverage.",
    price: 14.99,
    originalPrice: 21.99,
    rating: 4.6,
    ratingCount: 28,
    salesCount: 172,
    sellerId: "seller-2",
    categoryId: "capcut",
    productType: "VOUCHER_CODE",
    deliveryType: "INSTANT",
    status: "PUBLISHED",
    verified: true,
    smart: false,
    coverage: "Global",
    validity: "30 days",
    refundPolicy: "Refund if redemption fails.",
    termsOfUse: "Single creator usage only.",
    whatYouReceive: ["Voucher code", "Editor quickstart", "Support contact"],
    faq,
    cover: { from: "#7f1d1d", via: "#ef4444", to: "#f97316", glyph: "CC", eyebrow: "TRENDING" },
  },
  {
    id: "p-ai-service",
    slug: "ai-ops-setup-consulting",
    title: "AI Ops Setup Consulting",
    shortDescription:
      "Manual delivery consulting service for onboarding prompts, workflows, and team SOPs.",
    description:
      "A structured service package with kickoff, implementation checklist, and final handoff for startups moving from trial usage into process.",
    price: 249,
    originalPrice: 349,
    rating: 5,
    ratingCount: 16,
    salesCount: 53,
    sellerId: "seller-3",
    categoryId: "services",
    productType: "SERVICE",
    deliveryType: "MANUAL",
    status: "PUBLISHED",
    verified: false,
    smart: false,
    coverage: "Remote",
    validity: "One-off delivery",
    refundPolicy: "Refund before kickoff scheduling.",
    termsOfUse: "Scope limited to one implementation sprint.",
    whatYouReceive: ["Kickoff call", "Workflow blueprint", "Handoff notes"],
    faq,
    cover: { from: "#713f12", via: "#f59e0b", to: "#f97316", glyph: "OPS", eyebrow: "SERVICE" },
  },
];

export function getCategory(slug: string) {
  return demoCategories.find((category) => category.slug === slug);
}

export function getSeller(id: string) {
  return demoSellers.find((seller) => seller.id === id);
}

export function getProduct(slug: string, customProducts: DemoProduct[] = []) {
  return [...demoProducts, ...customProducts].find((product) => product.slug === slug);
}
